AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Instance & SecurityGroup create

Parameters:
  Ec2ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  SSHLocation:
    Description: IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:     
# ------------------------------------------------------------#
# Instance Srcurity Groups
# ------------------------------------------------------------# 
  EC2Sg1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: connect with ssh and webservice
      VpcId: !ImportValue CFn-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: CFn-ec2-sg
# ------------------------------------------------------------#
# EC2 Create
# ------------------------------------------------------------#
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Ec2ImageId
      KeyName: shipo4%
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue CFn-public-subnet-1a
          GroupSet:
            - !Ref EC2Sg1
      UserData: !Base64 |
        #!/bin/bash
        sudo yum install -y git
      Tags:
        - Key: Name
          Value: CFn-ec2
# ------------------------------------------------------------#
# EIP Association
# ------------------------------------------------------------#
  IPAssoc:
        Type: AWS::EC2::EIPAssociation
        Properties:
            InstanceId: !Ref EC2Instance1
            EIP: 35.73.197.99
# ------------------------------------------------------------#
# S3 Create
# ------------------------------------------------------------#
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: cfn-ec2-bucket
      AccessControl: Private
      VersioningConfiguration: 
        Status: Enabled
      Tags:
        - Key: Name
          Value: CFn-S3
# ------------------------------------------------------------#
# Outputs
# ------------------------------------------------------------#          
Outputs:
  StackEC2:
    Value: !Ref EC2Instance1
    Export:
      Name: CFn-ec2

  StackEC2Sg:
    Value: !Ref EC2Sg1
    Export:
      Name: CFn-ec2-sg