version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.0.1
  
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
            
  execute-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: deploy cfn
          command: |
            set -x
            aws cloudformation deploy --stack-name circleci-vpc --template-file cloudformation/Network.yml
            aws cloudformation deploy --stack-name circleci-ec2 --template-file cloudformation/EC2_S3.yml
            aws cloudformation deploy --stack-name circleci-rds --template-file cloudformation/RDS.yml
            aws cloudformation deploy --stack-name circleci-alb --template-file cloudformation/ALB.yml
      - run:
          name: Extract RDS endpoint
          command: |
            mkdir -p /tmp/workspace
            RDS_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier CFn-rds \
            --query "DBInstances[*].Endpoint.Address" \
            --output text > /tmp/workspace/rds-endpoint.txt)
            cat /tmp/workspace/rds-endpoint.txt
           
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - rds-endpoint.txt
      - run:
          name: pwd
          command: pwd
          
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "05:63:33:68:59:f9:6e:c7:6d:fe:58:aa:d7:cf:fa:6f"
      - ansible-playbook/install:
          version: 2.9.23
      - run:
          name: pwd
          command: pwd 
      - run:
          name: ls
          command: ls -a
          
      # - attach_workspace:
      #     at: /tmp/workspace
      # - run:
      #     name: rds-endpoint.txt
      #     command: cat /tmp/workspace/rds-endpoint.txt
      
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-i ansible/inventory'
          
  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Serverspec
          command: gem install serverspec
      - run:
          name: Run Serverspec tests
          command: |
            # Define the target host
            echo "Host target" > ~/.ssh/config
            echo "  HostName 54.250.92.188" >> ~/.ssh/config
            echo "  User ec2-user" >> ~/.ssh/config
            echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
            echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
            echo "  StrictHostKeyChecking no" >> ~/.ssh/config
            echo "  PasswordAuthentication no" >> ~/.ssh/config
            echo "  IdentitiesOnly yes" >> ~/.ssh/config
            echo "  LogLevel FATAL" >> ~/.ssh/config

            # Run serverspec
            cd serverspec
            rake spec
            
workflows:
  raisetech:
    jobs:
      - cfn-lint
      - execute-cfn
      - execute-ansible
      - execute-serverspec:
          requires:
            - execute-ansible
      
