version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
            
  execut-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: deploy cfn
          command: |
            set -x
            aws cloudformation deploy --stack-name circleci-vpc --template-file cloudformation/Network.yml
            aws cloudformation deploy --stack-name circleci-ec2 --template-file cloudformation/EC2_S3.yml
            aws cloudformation deploy --stack-name circleci-rds --template-file cloudformation/RDS.yml
            aws cloudformation deploy --stack-name circleci-alb --template-file cloudformation/ALB.yml
            
            
            
            
workflows:
  raisetech:
    jobs:
      - cfn-lint
      - execut-cfn
      
