---
- hosts: server
  become: true
  tasks:
  - name: package update
    yum:
      name: "*"
      state: least
      
  - name: Install required packages
    yum:
      name:
        - gcc-c++
        - make
        - patch
        - git
        - curl
        - zlib-devel
        - openssl-devel
        - ImageMagick-devel
        - readline-devel
        - libcurl-devel
        - libffi-devel
        - libicu-devel
        - libxml2-devel
        - libxslt-devel 
      state: present
      
  - name: Install Node.js
    yum:
      name: nodejs
      state: present
      
  - name: Install Yarn
    yum:
      name: yarn
      state: present

  - name: Clone rbenv repository
    git:
      repo: "https://github.com/rbenv/rbenv.git"
      dest: "~/.rbenv"
      version: master

  - name: Set rbenv environment variables
    lineinfile:
      dest: "~/.bashrc"
      line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
      create: yes

  - name: Initialize rbenv
    shell: |
      source ~/.bashrc
      eval "$(rbenv init -)"
    args:
      executable: /bin/bash

  - name: Install rbenv plugins
    git:
      repo: "https://github.com/rbenv/ruby-build.git"
      dest: "~/.rbenv/plugins/ruby-build"
      version: master

  - name: Set default Ruby version
    lineinfile:
      dest: "~/.bashrc"
      line: 'eval "$(rbenv init -)"'
      insertbefore: '^export PATH'
    args:
        state: present   
        
  - name: Clone ruby-build repository
    git:
 　    repo: "https://github.com/rbenv/ruby-build.git"
      dest: "~/.rbenv/plugins/ruby-build"
      version: master