---
- hosts: server
  become: true
  become_user: ec2-user
  tasks:
  
# ------------------------------------------------------------#
# Update Package
# ------------------------------------------------------------#
  - name: package update
    become_user: root
    yum:
      name: "*"
      state: latest
      
# ------------------------------------------------------------#
# Install Package For Rails
# ------------------------------------------------------------#
  - name: Install required packages
    become_user: root
    yum:
      name:
        - gcc-c++
        - make
        - patch
        - git
        - curl
        - zlib-devel
        - openssl-devel
        - ImageMagick-devel
        - readline-devel
        - libcurl-devel
        - libffi-devel
        - libicu-devel
        - libxml2-devel
        - libxslt-devel 
      state: present
      
# ------------------------------------------------------------#
# Install Node.js
# ------------------------------------------------------------#
  - name: Check if Node.js Yum repo file exists
    stat:
      path: /etc/yum.repos.d/nodesource-el7.repo
    register: nodesource_repo
    
  - name: Add Yum repo for Node.js
    become_user: root
    shell: "curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -"
    when: not nodesource_repo.stat.exists
    changed_when: false
    
  - name: Install Node.js
    become_user: root
    yum:
      name: nodejs
      state: latest
      
# ------------------------------------------------------------#
# Install Yarn
# ------------------------------------------------------------#
  - name: Check if Yarn Yum repo file exists
    stat:
      path: /etc/yum.repos.d/yarn.repo
    register: yarn_repo
    
  - name: Add Yum repo for Yarn
    become_user: root
    shell: "curl -fsSL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
    when: not yarn_repo.stat.exists
    changed_when: false
    
  - name: Install Yarn
    become_user: root
    yum:
      name: yarn
      state: latest
  
# ------------------------------------------------------------#
# Install rvenv
# ------------------------------------------------------------#   

  - name: Clone rbenv repository
    git:
      repo: "https://github.com/sstephenson/rbenv.git"
      dest: "/home/ec2-user/.rbenv"
      version: master

  - name: Add rbenv path to .bash_profile
    lineinfile:
      path: /home/ec2-user/.bash_profile
      line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
      create: yes

  - name: Initialize rbenv
    lineinfile:
      path: /home/ec2-user/.bash_profile
      line: 'eval "$(rbenv init -)"'
      create: yes

  - name: Load .bash_profile
    shell: bash -lc "source /home/ec2-user/.bash_profile"
    
  - name: Install rbenv plugins
    git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: "/home/ec2-user/.rbenv/plugins/ruby-build"
      
# ------------------------------------------------------------#
# Install Ruby
# ------------------------------------------------------------#
  - name: Check if Ruby is installed
    stat:
      path: /home/ec2-user/.rbenv/versions/3.1.2
    register: ruby_check
      
  - name: Install Ruby 3.1.2
    shell: bash -lc "rbenv install 3.1.2"
    when: not ruby_check.stat.exists
    
  - name: Rehash rbenv
    shell: bash -lc "rbenv rehash"
 
  - name: Set global Ruby version to 3.1.2
    shell: bash -lc "rbenv global 3.1.2"
    
# ------------------------------------------------------------#
# Install Rails
# ------------------------------------------------------------#
  - name: Check if Rails is installed
    shell: bash -lc "gem list -e rails | grep 7.0.4"
    register: rails_check
    changed_when: no
    ignore_errors: yes

  - name: Install Rails 7.0.4
    gem:
      name: rails
      version: 7.0.4
      user_install: no
      executable: /home/ec2-user/.rbenv/shims/gem
    when: rails_check is failed
    
# ------------------------------------------------------------#
# Install MySQL
# ------------------------------------------------------------#

  - name: Import MySQL GPG key
    shell: sudo rpm --import "https://repo.mysql.com/RPM-GPG-KEY-mysql-2022"
    args:
      creates: /var/lib/mysql/mysql80-community-release-el7-7.noarch.rpm

  - name: Download and install MySQL repository package
    shell: sudo rpm -Uvh "https://dev.mysql.com/get/mysql80-community-release-el7-7.noarch.rpm"
    args:
      creates: /etc/yum.repos.d/mysql-community.repo
      
  - name: Install mysql-devel
    become_user: root
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - mysql-server
      - mysql-devel
      - mysql-community-devel
      - mysql-community-server
    when: "'mysql' not in ansible_facts.packages"
    
# ------------------------------------------------------------#
# Clone APP
# ------------------------------------------------------------#
      
  - name: Clone repository
    git:
      repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
      dest: /home/ec2-user/raisetech-live8-sample-app
      
  - name: Change directory
    shell: cd raisetech-live8-sample-app

  - name: Install Bundler
    command: gem install bundler
    args:
      chdir: /raisetech-live8-sample-app
      
  # - name: Rename database.yml.sample
  #   command: mv config/database.yml.sample config/database.yml

  # - name: Read database.yml
  #   slurp:
  #     src: /raisetech-live8-sample-app/config/database.yml
  #   register: database_yml

  # - name: Modify database.yml (socket)
  #   replace:
  #     path: /raisetech-live8-sample-app/config/database.yml
  #     regexp: 'socket:.*'
  #     replace: 'socket: /var/lib/mysql/mysql.sock'
  #   when: "'socket:' in database_yml.content | b64decode"

  # - name: Modify database.yml (host)
  #   replace:
  #     path: /raisetech-live8-sample-app/config/database.yml
  #     regexp: 'host:.*'
  #     replace: 'host: circleci-rds-rdsinstance1-mayp2egjkjlf.ceyjn4b1ovyk.ap-northeast-1.rds.amazonaws.com'
  #   when: "'host:' not in database_yml.content | b64decode"

  # - name: Add host to database.yml
  #   lineinfile:
  #     path: /raisetech-live8-sample-app/config/database.yml
  #     line: '  host: circleci-rds-rdsinstance1-mayp2egjkjlf.ceyjn4b1ovyk.ap-northeast-1.rds.amazonaws.com'
  #   when: "'host:' not in database_yml.content | b64decode"