---
- hosts: server
  become: true
  tasks:
  - name: package update
    yum:
      name: "*"
      state: latest
      
  - name: Install required packages
    yum:
      name:
        - gcc-c++
        - make
        - patch
        - git
        - curl
        - zlib-devel
        - openssl-devel
        - ImageMagick-devel
        - readline-devel
        - libcurl-devel
        - libffi-devel
        - libicu-devel
        - libxml2-devel
        - libxslt-devel 
      state: present
  
  - name: Check if Node.js Yum repo file exists
    stat:
      path: /etc/yum.repos.d/nodesource-el7.repo
    register: nodesource_repo
    
  - name: Add Yum repo for Node.js
    shell: "curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -"
    when: not nodesource_repo.stat.exists
    changed_when: false
    
  - name: Install Node.js
    yum:
      name: nodejs
      state: latest
      
  - name: Check if Yarn Yum repo file exists
    stat:
      path: /etc/yum.repos.d/yarn.repo
    register: yarn_repo
    
  - name: Add Yum repo for Yarn
    shell: "curl -fsSL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"
    when: not yarn_repo.stat.exists
    changed_when: false
    
  - name: Install Yarn
    yum:
      name: yarn
      state: latest
      
  
  - name: Clone rbenv repository
    git:
      repo: "https://github.com/sstephenson/rbenv.git"
      dest: "/home/ec2-user/.rbenv"
      version: master
      
  - name: Add rbenv path to .bash_profile
    lineinfile:
      path: /home/ec2-user/.bash_profile
      line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
      create: yes

  - name: Initialize rbenv
    lineinfile:
      path: /home/ec2-user/.bash_profile
      line: 'eval "$(rbenv init -)"'
      create: yes

  - name: Load .bash_profile
    shell: "source /home/ec2-user/.bash_profile"

      
  - name: Install rbenv plugins
    git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: "/home/ec2-user/.rbenv/plugins/ruby-build"
      version: masters
  
  - name: Install Ruby 3.1.2
    shell: "rbenv install 3.1.2"
    
  # - name: Rehash rbenv
  #   shell: rbenv rehash
  #   args:
  #     executable: /bin/bash
 
  # - name: Set global Ruby version to 3.1.2
  #   shell: rbenv global 3.1.2
  #   args:
  #     executable: /bin/bash

   # - name: Install Rails 7.0.4
  #   gem:
  #     name: rails
  #     version: 7.0.4
  #     state: present
  #     executable: /home/{{ ansible_user }}/.rbenv/shims/gem
  #   become_user: "{{ ansible_user }}"
  
  # - name: Download MySQL repository configuration file
  #   command: wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

  # - name: Install MySQL repository
  #   command: rpm -ivh mysql80-community-release-el7-3.noarch.rpm

  # - name: Install MySQL server
  #   yum:
  #     name: mysql-server
  #     state: present

  # - name: Start MySQL service
  #   service:
  #     name: mysqld
  #     state: started
  #     enabled: yes
      
  # - name: Install MySQL Community Development Packages
  #   yum:
  #     name: "{{ item }}"
  #     state: present
  #   with_items:
  #     - mysql-community-devel
  #     - mysql-community-server
      
  # - name: Clone repository
  #   git:
  #     repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
  #     dest: .
      
  # - name: Change directory
  #   shell: cd raisetech-live8-sample-app

  # - name: Install Bundler
  #   command: gem install bundler
  #   args:
  #     chdir: /raisetech-live8-sample-app
      
  # - name: Rename database.yml.sample
  #   command: mv config/database.yml.sample config/database.yml

  # - name: Read database.yml
  #   slurp:
  #     src: /raisetech-live8-sample-app/config/database.yml
  #   register: database_yml

  # - name: Modify database.yml (socket)
  #   replace:
  #     path: /raisetech-live8-sample-app/config/database.yml
  #     regexp: 'socket:.*'
  #     replace: 'socket: /var/lib/mysql/mysql.sock'
  #   when: "'socket:' in database_yml.content | b64decode"

  # - name: Modify database.yml (host)
  #   replace:
  #     path: /raisetech-live8-sample-app/config/database.yml
  #     regexp: 'host:.*'
  #     replace: 'host: circleci-rds-rdsinstance1-mayp2egjkjlf.ceyjn4b1ovyk.ap-northeast-1.rds.amazonaws.com'
  #   when: "'host:' not in database_yml.content | b64decode"

  # - name: Add host to database.yml
  #   lineinfile:
  #     path: /raisetech-live8-sample-app/config/database.yml
  #     line: '  host: circleci-rds-rdsinstance1-mayp2egjkjlf.ceyjn4b1ovyk.ap-northeast-1.rds.amazonaws.com'
  #   when: "'host:' not in database_yml.content | b64decode"